### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by pedenys** [barelyhuman/reaper.is#2]
Hi !

I would like to follow your blog using RSS.

I see your website is currently done using Astro. I've never used it but I wouldn't mind having a look at it and submitting a PR to add an RSS feed. It seems quite doable according to the [docs](https://docs.astro.build/en/guides/rss/))

Tell me if you're interested.

Thanks

**Comment by barelyhuman** [comment]
I had feeds on my older blogs, 
I didn't add in this one since I'm still working on adding tags and other stuff, 

since you've requested it, I'll move the feed addition to be done first

**Comment by barelyhuman** [comment]
auto-redirect for rss added on: https://reaper.im
if the feed reader doesn't use the redirect: you can manually put in this url https://reaper.im/rss.xml

**Comment by pedenys** [comment]
(Many thanks !)
